/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TanstackIntermediateFormRouteRouteImport } from './routes/tanstack-intermediate-form/route'
import { Route as ReactHookSampleRouteRouteImport } from './routes/react-hook-sample/route'
import { Route as ReactHookIntermediateFormRouteRouteImport } from './routes/react-hook-intermediate-form/route'
import { Route as FormikSampleRouteRouteImport } from './routes/formik-sample/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TanstackIntermediateFormViewRouteRouteImport } from './routes/tanstack-intermediate-form/view/route'
import { Route as TanstackIntermediateFormEditRouteRouteImport } from './routes/tanstack-intermediate-form/edit/route'
import { Route as TanstackIntermediateFormAddRouteRouteImport } from './routes/tanstack-intermediate-form/add/route'

const TanstackIntermediateFormRouteRoute =
  TanstackIntermediateFormRouteRouteImport.update({
    id: '/tanstack-intermediate-form',
    path: '/tanstack-intermediate-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReactHookSampleRouteRoute = ReactHookSampleRouteRouteImport.update({
  id: '/react-hook-sample',
  path: '/react-hook-sample',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactHookIntermediateFormRouteRoute =
  ReactHookIntermediateFormRouteRouteImport.update({
    id: '/react-hook-intermediate-form',
    path: '/react-hook-intermediate-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormikSampleRouteRoute = FormikSampleRouteRouteImport.update({
  id: '/formik-sample',
  path: '/formik-sample',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TanstackIntermediateFormViewRouteRoute =
  TanstackIntermediateFormViewRouteRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => TanstackIntermediateFormRouteRoute,
  } as any)
const TanstackIntermediateFormEditRouteRoute =
  TanstackIntermediateFormEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TanstackIntermediateFormRouteRoute,
  } as any)
const TanstackIntermediateFormAddRouteRoute =
  TanstackIntermediateFormAddRouteRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => TanstackIntermediateFormRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formik-sample': typeof FormikSampleRouteRoute
  '/react-hook-intermediate-form': typeof ReactHookIntermediateFormRouteRoute
  '/react-hook-sample': typeof ReactHookSampleRouteRoute
  '/tanstack-intermediate-form': typeof TanstackIntermediateFormRouteRouteWithChildren
  '/tanstack-intermediate-form/add': typeof TanstackIntermediateFormAddRouteRoute
  '/tanstack-intermediate-form/edit': typeof TanstackIntermediateFormEditRouteRoute
  '/tanstack-intermediate-form/view': typeof TanstackIntermediateFormViewRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formik-sample': typeof FormikSampleRouteRoute
  '/react-hook-intermediate-form': typeof ReactHookIntermediateFormRouteRoute
  '/react-hook-sample': typeof ReactHookSampleRouteRoute
  '/tanstack-intermediate-form': typeof TanstackIntermediateFormRouteRouteWithChildren
  '/tanstack-intermediate-form/add': typeof TanstackIntermediateFormAddRouteRoute
  '/tanstack-intermediate-form/edit': typeof TanstackIntermediateFormEditRouteRoute
  '/tanstack-intermediate-form/view': typeof TanstackIntermediateFormViewRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formik-sample': typeof FormikSampleRouteRoute
  '/react-hook-intermediate-form': typeof ReactHookIntermediateFormRouteRoute
  '/react-hook-sample': typeof ReactHookSampleRouteRoute
  '/tanstack-intermediate-form': typeof TanstackIntermediateFormRouteRouteWithChildren
  '/tanstack-intermediate-form/add': typeof TanstackIntermediateFormAddRouteRoute
  '/tanstack-intermediate-form/edit': typeof TanstackIntermediateFormEditRouteRoute
  '/tanstack-intermediate-form/view': typeof TanstackIntermediateFormViewRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formik-sample'
    | '/react-hook-intermediate-form'
    | '/react-hook-sample'
    | '/tanstack-intermediate-form'
    | '/tanstack-intermediate-form/add'
    | '/tanstack-intermediate-form/edit'
    | '/tanstack-intermediate-form/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formik-sample'
    | '/react-hook-intermediate-form'
    | '/react-hook-sample'
    | '/tanstack-intermediate-form'
    | '/tanstack-intermediate-form/add'
    | '/tanstack-intermediate-form/edit'
    | '/tanstack-intermediate-form/view'
  id:
    | '__root__'
    | '/'
    | '/formik-sample'
    | '/react-hook-intermediate-form'
    | '/react-hook-sample'
    | '/tanstack-intermediate-form'
    | '/tanstack-intermediate-form/add'
    | '/tanstack-intermediate-form/edit'
    | '/tanstack-intermediate-form/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormikSampleRouteRoute: typeof FormikSampleRouteRoute
  ReactHookIntermediateFormRouteRoute: typeof ReactHookIntermediateFormRouteRoute
  ReactHookSampleRouteRoute: typeof ReactHookSampleRouteRoute
  TanstackIntermediateFormRouteRoute: typeof TanstackIntermediateFormRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanstack-intermediate-form': {
      id: '/tanstack-intermediate-form'
      path: '/tanstack-intermediate-form'
      fullPath: '/tanstack-intermediate-form'
      preLoaderRoute: typeof TanstackIntermediateFormRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-hook-sample': {
      id: '/react-hook-sample'
      path: '/react-hook-sample'
      fullPath: '/react-hook-sample'
      preLoaderRoute: typeof ReactHookSampleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-hook-intermediate-form': {
      id: '/react-hook-intermediate-form'
      path: '/react-hook-intermediate-form'
      fullPath: '/react-hook-intermediate-form'
      preLoaderRoute: typeof ReactHookIntermediateFormRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formik-sample': {
      id: '/formik-sample'
      path: '/formik-sample'
      fullPath: '/formik-sample'
      preLoaderRoute: typeof FormikSampleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanstack-intermediate-form/view': {
      id: '/tanstack-intermediate-form/view'
      path: '/view'
      fullPath: '/tanstack-intermediate-form/view'
      preLoaderRoute: typeof TanstackIntermediateFormViewRouteRouteImport
      parentRoute: typeof TanstackIntermediateFormRouteRoute
    }
    '/tanstack-intermediate-form/edit': {
      id: '/tanstack-intermediate-form/edit'
      path: '/edit'
      fullPath: '/tanstack-intermediate-form/edit'
      preLoaderRoute: typeof TanstackIntermediateFormEditRouteRouteImport
      parentRoute: typeof TanstackIntermediateFormRouteRoute
    }
    '/tanstack-intermediate-form/add': {
      id: '/tanstack-intermediate-form/add'
      path: '/add'
      fullPath: '/tanstack-intermediate-form/add'
      preLoaderRoute: typeof TanstackIntermediateFormAddRouteRouteImport
      parentRoute: typeof TanstackIntermediateFormRouteRoute
    }
  }
}

interface TanstackIntermediateFormRouteRouteChildren {
  TanstackIntermediateFormAddRouteRoute: typeof TanstackIntermediateFormAddRouteRoute
  TanstackIntermediateFormEditRouteRoute: typeof TanstackIntermediateFormEditRouteRoute
  TanstackIntermediateFormViewRouteRoute: typeof TanstackIntermediateFormViewRouteRoute
}

const TanstackIntermediateFormRouteRouteChildren: TanstackIntermediateFormRouteRouteChildren =
  {
    TanstackIntermediateFormAddRouteRoute:
      TanstackIntermediateFormAddRouteRoute,
    TanstackIntermediateFormEditRouteRoute:
      TanstackIntermediateFormEditRouteRoute,
    TanstackIntermediateFormViewRouteRoute:
      TanstackIntermediateFormViewRouteRoute,
  }

const TanstackIntermediateFormRouteRouteWithChildren =
  TanstackIntermediateFormRouteRoute._addFileChildren(
    TanstackIntermediateFormRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormikSampleRouteRoute: FormikSampleRouteRoute,
  ReactHookIntermediateFormRouteRoute: ReactHookIntermediateFormRouteRoute,
  ReactHookSampleRouteRoute: ReactHookSampleRouteRoute,
  TanstackIntermediateFormRouteRoute:
    TanstackIntermediateFormRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
